import os
import django
from django.core.files.base import ContentFile

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from products.models import PostLink

def run():
    # Clear existing post links to avoid duplicates
    PostLink.objects.all().delete()
    
    post_links_data = [
        {
            "title": "Articulated Dragon 3D Model", 
            "link": "https://makerworld.com/en/models/123", 
            "show_for_youtube": True, 
            "show_for_tiktok": True, 
            "show_for_instagram": False, 
            "is_pinned": True,
            "image_path": "/Users/jahongirmirzo/.gemini/antigravity/brain/e75515a2-f57a-40c8-a1c7-21d9e2d264e7/tech_gadget_1781026838033.png"
        },
        {
            "title": "Smart Home Hub Case", 
            "link": "https://printables.com/model/456", 
            "show_for_youtube": True, 
            "show_for_tiktok": True, 
            "show_for_instagram": True, 
            "is_pinned": False,
            "image_path": "/Users/jahongirmirzo/.gemini/antigravity/brain/e75515a2-f57a-40c8-a1c7-21d9e2d264e7/home_hub_1781026850992.png"
        },
        {
            "title": "Headphone Stand 3D Print", 
            "link": "https://makerworld.com/en/models/789", 
            "show_for_youtube": False, 
            "show_for_tiktok": True, 
            "show_for_instagram": True, 
            "is_pinned": False,
            "image_path": "/Users/jahongirmirzo/.gemini/antigravity/brain/e75515a2-f57a-40c8-a1c7-21d9e2d264e7/headphones_1781026861701.png"
        },
        {
            "title": "Mechanical Keyboard Keycaps", 
            "link": "https://printables.com/model/012", 
            "show_for_youtube": True, 
            "show_for_tiktok": False, 
            "show_for_instagram": True, 
            "is_pinned": False,
            "image_path": "/Users/jahongirmirzo/.gemini/antigravity/brain/e75515a2-f57a-40c8-a1c7-21d9e2d264e7/keyboard_1781026873523.png"
        },
    ]

    count = 0
    for data in post_links_data:
        image_path = data.pop("image_path")
        p = PostLink(**data)
        
        # Read the real image generated by AI
        try:
            with open(image_path, "rb") as f:
                file_name = f"{data['title'].replace(' ', '_').lower()}.png"
                p.file.save(file_name, ContentFile(f.read()), save=False)
        except Exception as e:
            print(f"Failed to read image at {image_path}: {e}")
            
        p.save()
        count += 1
        print(f"Created Post Link: {p.title}")

    print(f"Successfully populated database with {count} post links.")

if __name__ == '__main__':
    run()
