# Generated by Django 5.2.7 on 2025-10-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It will be displayed as the product name on the card', max_length=255)),
                ('link', models.URLField(help_text='Link to the product page')),
                ('show_for_youtube', models.BooleanField(default=True, help_text='If checked, the product will be shown for YouTube domain', verbose_name='Show for YouTube')),
                ('show_for_tiktok', models.BooleanField(default=True, help_text='If checked, the product will be shown for TikTok domain', verbose_name='Show for TikTok')),
                ('show_for_instagram', models.BooleanField(default=True, help_text='If checked, the product will be shown for Instagram domain', verbose_name='Show for Instagram')),
                ('is_pinned', models.BooleanField(default=False, help_text='If checked, the product will be pinned at the top of the list', verbose_name='Pin?')),
                ('file', models.FileField(help_text='Upload a file related to the product (e.g., image, gif)', upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
