# Generated by Django 5.2.7 on 2025-10-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_pinned', '-order', '-published_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
