# Generated by Django 5.2.7 on 2025-10-18 14:23

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.FloatField(default=products.models.default_order, help_text='The order of the product', verbose_name='Order'),
        ),
    ]
