# Generated by Django 5.2.7 on 2025-10-18 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The date and time when the product was published', null=True, verbose_name='Published At'),
        ),
    ]
