# Generated by Django 5.2.7 on 2025-10-18 14:19

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_pinned', 'order', '-published_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.FloatField(default=products.models.default_order, help_text='The order of the product', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the product was published', null=True, verbose_name='Published At'),
        ),
    ]
