# Generated by Django 5.2.7 on 2026-06-09 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_postlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlink',
            options={'ordering': ['-is_pinned', '-order', '-published_at'], 'verbose_name': 'Post Link', 'verbose_name_plural': 'Post Links'},
        ),
        migrations.AlterField(
            model_name='postlink',
            name='file',
            field=models.FileField(help_text='Upload an image or file related to the post link', upload_to='post_links/'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If checked, the post link will be pinned at the top of the list', verbose_name='Pin?'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='link',
            field=models.URLField(help_text='Link to the external product/post page'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='order',
            field=models.FloatField(blank=True, help_text='The order of the post link', null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The date and time when the post link was published', null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='show_for_instagram',
            field=models.BooleanField(default=True, help_text='If checked, the post link will be shown for Instagram domain', verbose_name='Show for Instagram'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='show_for_tiktok',
            field=models.BooleanField(default=True, help_text='If checked, the post link will be shown for TikTok domain', verbose_name='Show for TikTok'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='show_for_youtube',
            field=models.BooleanField(default=True, help_text='If checked, the post link will be shown for YouTube domain', verbose_name='Show for YouTube'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='title',
            field=models.CharField(help_text='It will be displayed as the 3D model/post link name on the card', max_length=255),
        ),
    ]
